# Generated by Django 4.0.3 on 2023-11-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=30)),
                ('hotel_about', models.CharField(max_length=50)),
                ('hotel_feature1', models.CharField(max_length=10)),
                ('hotel_feature2', models.CharField(max_length=10)),
                ('hotel_feature3', models.CharField(max_length=10)),
                ('hotel_feature4', models.CharField(max_length=10)),
                ('hotel_feature5', models.CharField(max_length=10)),
                ('hotel_image1', models.FileField(default=None, max_length=250, null=True, upload_to='hotel/')),
                ('hotel_image2', models.FileField(default=None, max_length=250, null=True, upload_to='hotel/')),
                ('hotel_image3', models.FileField(default=None, max_length=250, null=True, upload_to='hotel/')),
                ('hotel_image4', models.FileField(default=None, max_length=250, null=True, upload_to='hotel/')),
                ('hotel_image5', models.FileField(default=None, max_length=250, null=True, upload_to='hotel/')),
            ],
        ),
        migrations.CreateModel(
            name='Murshidabad_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='murshidabad_place/')),
            ],
        ),
        migrations.CreateModel(
            name='Murshidabad_Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('restaurant', models.ImageField(upload_to='restaurant_images/')),
                ('menu', models.ImageField(upload_to='restaurant_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='review/')),
                ('name', models.CharField(max_length=100)),
                ('review', models.TextField()),
                ('stars', models.IntegerField(choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Not Specified')], max_length=1)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
