# Generated by Django 4.2.4 on 2023-10-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=30)),
                ('hotel_about', models.CharField(max_length=50)),
                ('hotel_feature1', models.CharField(max_length=10)),
                ('hotel_feature2', models.CharField(max_length=10)),
                ('hotel_feature3', models.CharField(max_length=10)),
                ('hotel_feature4', models.CharField(max_length=10)),
                ('hotel_feature5', models.CharField(max_length=10)),
                ('hotel_image1', models.FileField(default=None, max_length=250, null=True, upload_to='hotel/')),
                ('hotel_image2', models.FileField(default=None, max_length=250, null=True, upload_to='hotel/')),
                ('hotel_image3', models.FileField(default=None, max_length=250, null=True, upload_to='hotel/')),
                ('hotel_image4', models.FileField(default=None, max_length=250, null=True, upload_to='hotel/')),
                ('hotel_image5', models.FileField(default=None, max_length=250, null=True, upload_to='hotel/')),
            ],
        ),
    ]
