# Generated by Django 4.2.4 on 2023-11-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_review'),
        ('myapp', '0002_remove_user_image_user_picture_alter_user_password'),
    ]

    operations = [
    ]
