# Generated by Django 4.0.3 on 2023-11-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='murshidabad_restaurants',
            name='Dist',
            field=models.CharField(default='valid python', max_length=100),
            preserve_default=False,
        ),
    ]
