# Generated by Django 4.0.3 on 2023-11-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_user_image_user_picture_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murshidabad_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='murshidabad_place/')),
            ],
        ),
    ]
