# Generated by Django 4.0.3 on 2023-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_murshidabad_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murshidabad_Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('restaurant', models.ImageField(upload_to='restaurant_images/')),
                ('menu', models.ImageField(upload_to='restaurant_images/')),
            ],
        ),
    ]
