# Generated by Django 4.0.3 on 2023-11-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='review/'),
        ),
    ]
