# Generated by Django 4.0.3 on 2023-11-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_murshidabad_restaurants_dist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Murshidabad_Restaurants',
            new_name='Restaurants',
        ),
    ]
