# Generated by Django 4.0.3 on 2023-11-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_murshidabad_restaurants_restaurants'),
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('Dist', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='murshidabad_place/')),
            ],
        ),
        migrations.DeleteModel(
            name='Murshidabad_place',
        ),
    ]
