# Generated by Django 4.0.3 on 2023-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_place_delete_murshidabad_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_dist',
            field=models.CharField(default='murshidabad', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(upload_to='place/'),
        ),
    ]
