# Generated by Django 4.0.3 on 2023-11-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_hotel_hotel_dist_hotel_hotel_price_alter_place_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_dist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
