# Generated by Django 4.0.3 on 2023-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_hotel_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
