# Generated by Django 4.0.3 on 2023-11-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_hotelbooking_hotelbookingmemberdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='total_member',
            field=models.IntegerField(null=True),
        ),
    ]
