# Generated by Django 4.0.3 on 2023-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_hotelbooking_total_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='total_member',
            field=models.IntegerField(default=0),
        ),
    ]
