# Generated by Django 4.0.3 on 2023-11-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_hotelbooking_total_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='total_member',
        ),
        migrations.AlterField(
            model_name='hotelbookingmemberdetail',
            name='hotel_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotel_booking_members', to='myapp.hotelbooking'),
        ),
    ]
