# Generated by Django 4.0.3 on 2023-11-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_hotelbooking_total_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='allowed_number',
            field=models.IntegerField(default=2),
        ),
    ]
