# Generated by Django 4.0.3 on 2023-11-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_hotel_allowed_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbookingmemberdetail',
            name='aadhaar_no',
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='aadhaar_no',
            field=models.IntegerField(null=True),
        ),
    ]
